# Setting your passwords and create you personal db user
version: "3.6"

networks:
  mei-network:

services:
  mei-mysql:
    image: anto6715/bluecloud_mysql:latest
    networks:
      - mei-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD={{ cmmc_mysql_root_password }}
      - MYSQL_PASSWORD={{ cmmc_mysql_password }}
      - MYSQL_USER=mei
      - MYSQL_DATABASE=seastat
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1234:80"
    networks:
      - mei-network
    environment:
      - PMA_HOST=mei-mysql
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-register:
    image: anto6715/bluecloud-register:latest
    ports:
      - "8080:8080"
    networks:
      - mei-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mei-mysql:3306/seastat
      - SPRING_DATASOURCE_USERNAME=mei
      - SPRING_DATASOURCE_PASSWORD={{ cmmc_mysql_password }}
    depends_on:
      - mei-mysql
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webservice:
    image: fpalermo/bluecloud-webservice:latest
    networks:
      - mei-network
    ports:
      - "5000:80"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webapp:
    image: fpalermo/bluecloud-webapp:local
    networks:
      - mei-network
    ports:
      - "3000:80"
    depends_on:
      - mei-register
      - mei-webservice
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  