# Setting your passwords and create you personal db user
version: "3.6"

networks:
  mei-network-dev:

services:
  mei-mysql:
    image: mysql:8
    networks:
      - mei-network-dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=mei
      - MYSQL_DATABASE=seastat
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1234:80"
    networks:
      - mei-network-dev
    environment:
      - PMA_HOST=mei-mysql
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-register:
    image: anto6715/bluecloud-register:dev
    ports:
      - "8080:8080"
    networks:
      - mei-network-dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mei-mysql:3306/seastat
      - SPRING_DATASOURCE_USERNAME=mei
      - SPRING_DATASOURCE_PASSWORD=test
    depends_on:
      - mei-mysql
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webservice:
    image: fpalermo/bluecloud-webservice:dev
    networks:
      - mei-network-dev
    ports:
      - "5000:80"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webapp:
    image: fpalermo/bluecloud-webapp:dev
    networks:
      - mei-network-dev
    ports:
      - "3000:80"
    depends_on:
      - mei-register
      - mei-webservice
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  