version: "3.6"

networks:
  haproxy-public:
    external: true
  mei-network:

services:
  mei-mysql:
    image: anto6715/bluecloud_mysql:latest
    networks:
      - mei-network
    environment:
      - MYSQL_ROOT_PASSWORD={{ cmmc_mysql_root_password }}
      - MYSQL_PASSWORD={{ cmmc_mysql_password }}
      - MYSQL_USER=mei
      - MYSQL_DATABASE=seastat
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - mei-network
      - haproxy-public
    environment:
      - PMA_HOST=mei-mysql
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-register:
    image: anto6715/bluecloud-register:latest
    networks:
      - mei-network
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webservice:
    image: fpalermo/bluecloud-webservice:latest
    networks:
      - mei-network
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
  mei-webapp:
    image: fpalermo/bluecloud-webapp:latest
    networks:
      - mei-network
      - haproxy-public
    depends_on:
      - mei-register
      - mei-webservice
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: 'journald'
